import sys
from models.naive_bayes.model import _LOADED_DATASETS, predict, predict_without_word, load_dataset, prepare_train

# 1. Load dataset and train model to populate _LOADED_DATASETS
print("Loading dataset...")
load_dataset({"dataset_id": "twenty_newsgroups"})

print("Training model...")
prepare_train({
    "dataset_id": "twenty_newsgroups",
    "alpha": 1.0,
    "remove_headers": True,
    "remove_quotes": True,
    "remove_footers": True,
    "remove_numbers": True,
    "lowercase": True,
    "remove_stopwords": True
})

print("Testing predict with preset text...")
text = "The flight dynamics team completed a small thruster burn to raise the orbit of the space telescope. The new orbital parameters are stable. We expect the satellite to remain in space for another decade."
res_predict = predict({
    "dataset_id": "twenty_newsgroups",
    "text": text
})
print("predict returns keys:", list(res_predict.keys()))
print("predict sample_index:", res_predict.get("sample_index"))
print("predict full_text:", res_predict.get("full_text") is not None)

print("Testing predict_without_word with payload generated by predict_page.js...")
# Simulate frontend payload construction:
# typeof nbPredictData.sample_index === "number" -> False (since it is None)
# payload.text = nbPredictData.full_text || window.nbPredictCustomText;
payload = {
    "dataset_id": "twenty_newsgroups",
    "removed_word": "space",
    "text": res_predict.get("full_text")
}
try:
    res_without = predict_without_word(payload)
    print("predict_without_word success!", res_without["message"])
except Exception as e:
    print("predict_without_word failed:", e)
